src/Entity/Pagedegarde.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PagedegardeRepository")
 */
class Pagedegarde
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $numero_copieoriginal;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $numero_copie1;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $numero_copie2;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $numero_copie3;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $numero_copie4;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $numero_copie5;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $numero_copiebureau;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $visualiser;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $fichier;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $nom_etablissement;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNumeroCopieoriginal(): ?string
    {
        return $this->numero_copieoriginal;
    }

    public function setNumeroCopieoriginal(string $numero_copieoriginal): self
    {
        $this->numero_copieoriginal = $numero_copieoriginal;

        return $this;
    }

    public function getNumeroCopie1(): ?string
    {
        return $this->numero_copie1;
    }

    public function setNumeroCopie1(string $numero_copie1): self
    {
        $this->numero_copie1 = $numero_copie1;

        return $this;
    }

    public function getNumeroCopie2(): ?string
    {
        return $this->numero_copie2;
    }

    public function setNumeroCopie2(string $numero_copie2): self
    {
        $this->numero_copie2 = $numero_copie2;

        return $this;
    }

    public function getNumeroCopie3(): ?string
    {
        return $this->numero_copie3;
    }

    public function setNumeroCopie3(string $numero_copie3): self
    {
        $this->numero_copie3 = $numero_copie3;

        return $this;
    }

    public function getNumeroCopie4(): ?string
    {
        return $this->numero_copie4;
    }

    public function setNumeroCopie4(string $numero_copie4): self
    {
        $this->numero_copie4 = $numero_copie4;

        return $this;
    }

    public function getNumeroCopie5(): ?string
    {
        return $this->numero_copie5;
    }

    public function setNumeroCopie5(string $numero_copie5): self
    {
        $this->numero_copie5 = $numero_copie5;

        return $this;
    }

    public function getNumeroCopiebureau(): ?string
    {
        return $this->numero_copiebureau;
    }

    public function setNumeroCopiebureau(string $numero_copiebureau): self
    {
        $this->numero_copiebureau = $numero_copiebureau;

        return $this;
    }

    public function getVisualiser(): ?string
    {
        return $this->visualiser;
    }

    public function setVisualiser(string $visualiser): self
    {
        $this->visualiser = $visualiser;

        return $this;
    }

    public function getFichier(): ?string
    {
        return $this->fichier;
    }

    public function setFichier(string $fichier): self
    {
        $this->fichier = $fichier;

        return $this;
    }

    public function getNomEtablissement(): ?string
    {
        return $this->nom_etablissement;
    }

    public function setNomEtablissement(?string $nom_etablissement): self
    {
        $this->nom_etablissement = $nom_etablissement;

        return $this;
    }
}

src/Form/PagedegardeType.php
<?php

namespace App\Form;

use App\Entity\Pagedegarde;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PagedegardeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('numero_copieoriginal')
            ->add('numero_copie1')
            ->add('numero_copie2')
            ->add('numero_copie3')
            ->add('numero_copie4')
            ->add('numero_copie5')
            ->add('numero_copiebureau')
            ->add('nom_etablissement')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Pagedegarde::class,
        ]);
    }
}

src/Controller/PagedegardeController.php
<?php

namespace App\Controller;

use App\Entity\Pagedegarde;
use App\Form\PagedegardeType;
use App\Repository\PagedegardeRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use setasign\Fpdi\Fpdi ;

/**
 * @Route("/pagedegarde")
 */
class PagedegardeController extends AbstractController
{
    /**
     * @Route("/", name="pagedegarde_index", methods={"GET"})
     */
    public function index(PagedegardeRepository $pagedegardeRepository): Response
    {
        return $this->render('pagedegarde/index.html.twig', [
            'pagedegardes' => $pagedegardeRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="pagedegarde_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $pagedegarde = new Pagedegarde();
        $form = $this->createForm(PagedegardeType::class, $pagedegarde);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($pagedegarde);
            $entityManager->flush();

            $file =  "C:\Users\Djiby sow\Desktop/2IRIS/2iris\public/page_de_garde/pages_de_garde.pdf";

            $newFile = "C:\Users\Djiby sow\Desktop/2IRIS/2iris\public/page_de_garde/pages_de_garde_".$pagedegarde->getId().".pdf";
            copy($file, $newFile );
            // initie FPDI 
            $pdf = new  Fpdi ();
           // ajoute une page 
            $pdf->AddPage ();
            // définit le fichier source 
            $pdf->setSourceFile($newFile);
             // page d'importation 1 
             $tplId = $pdf->importPage(1);
            // utilise la page importée et la place au point 10,10 avec une largeur de 100 mm 
            $pdf->useTemplate($tplId);
            //pour la gestion du font
            //getNomEtablissement()
            $pdf->SetFont ('Helvetica');
            $pdf->SetXY(10 ,18);
            $pdf->Cell(180,258, $pagedegarde->getNumeroCopieoriginal(),0,0,'C');
            $pdf->Cell(180,150, $pagedegarde->getNomEtablissement(),0,0,'C');
            $pdf->Cell(180,200, $pagedegarde->getNomEtablissement(),0,0,'C');
            //Ecrire sur le fichier
            //$pdf->Write( 8 , $lettreDeRetrait->getLieu(). ' le '. $lettreDeRetrait->getDate()->format('d M Y'));
              
            $tplId = $pdf->importPage(2);

            $pdf->AddPage ();
            // utilise la page importée et la place au point 10,10 avec une largeur de 100 mm 
            $pdf->useTemplate($tplId);
            //pour la gestion du font
            $pdf->SetFont ('Helvetica');
            //pour la gestion de la position
            $pdf->SetXY(10 ,18);
            $pdf->Cell(180,258, utf8_encode($pagedegarde->getNumeroCopie1()), 0, 0,'C');
            $pdf->Cell(180,258, $pagedegarde->getNomEtablissement(),0,0,'C');
            $pdf->Cell(180,258, $pagedegarde->getNomEtablissement(),0,0,'C');
            
            //Ecrire sur le fichier
            //$pdf->Write( 8 , $lettreDeRetrait->getDestinataire());
            
            $tplId = $pdf->importPage(3);

            $pdf->AddPage ();
            // utilise la page importée et la place au point 10,10 avec une largeur de 100 mm 
            $pdf->useTemplate($tplId);
            //pour la gestion du font
            $pdf->SetFont ('Helvetica');
            //pour la gestion de la position
            $pdf->SetXY(10 ,18);
            $pdf->Cell(180,258, $pagedegarde->getNumeroCopie2() , 0, 0,'C');
            $pdf->Cell(180,258, $pagedegarde->getNomEtablissement(),0,0,'C');
            $pdf->Cell(180,258, $pagedegarde->getNomEtablissement(),0,0,'C');
            //Ecrire sur le fichier
            //$pdf->Write( 8 , $lettreDeRetrait->getAdrDesti());
            
            $tplId = $pdf->importPage(4);

            $pdf->AddPage ();
            // utilise la page importée et la place au point 10,10 avec une largeur de 100 mm 
            $pdf->useTemplate($tplId);
            //pour la gestion du font
            $pdf->SetFont ('Helvetica');
            //pour la gestion de la position
            $pdf->SetXY(10 ,18);
            $pdf->Cell(180,258, $pagedegarde->getNumeroCopie3() , 0, 0,'C');
            $pdf->Cell(180,258, $pagedegarde->getNomEtablissement(),0,0,'C');
            $pdf->Cell(180,258, $pagedegarde->getNomEtablissement(),0,0,'C');
            //Ecrire sur le fichier
            //$pdf->Write( 8 , $lettreDeRetrait->getReference());
             
            $tplId = $pdf->importPage(5);

            $pdf->AddPage ();
            // utilise la page importée et la place au point 10,10 avec une largeur de 100 mm 
            $pdf->useTemplate($tplId);
            //pour la gestion du font
            $pdf->SetFont ('Helvetica');
            //pour la gestion de la position
            $pdf->SetXY(10 ,18);
            $pdf->Cell(180,258, $pagedegarde->getNumeroCopie4() , 0, 0,'C');
            $pdf->Cell(180,258, $pagedegarde->getNomEtablissement(),0,0,'C');
            $pdf->Cell(180,258, $pagedegarde->getNomEtablissement(),0,0,'C');

            
            $tplId = $pdf->importPage(6);

            $pdf->AddPage ();
            // utilise la page importée et la place au point 10,10 avec une largeur de 100 mm 
            $pdf->useTemplate($tplId);
            //pour la gestion du font
            $pdf->SetFont ('Helvetica');
              //pour la gestion de la position
             $pdf->SetXY(10 ,18);
             $pdf->Cell(180,252, $pagedegarde->getNumeroCopie5(), 0, 0,'C');
             $pdf->Cell(180,258, $pagedegarde->getNomEtablissement(),0,0,'C');
            $pdf->Cell(180,258, $pagedegarde->getNomEtablissement(),0,0,'C');

             
             $tplId = $pdf->importPage(7);

             $pdf->AddPage ();
             $pdf->useTemplate($tplId);
               //pour la gestion de la position
               //getNomEtablissement()
             $pdf->SetXY(10 ,18);
             $pdf->SetFont ('Helvetica');
             $pdf->Cell(180,258, $pagedegarde->getNumeroCopiebureau(), 0, 0,'C');
             $pdf->Cell(180,258, $pagedegarde->getNomEtablissement(),0,0,'C');
            $pdf->Cell(180,258, $pagedegarde->getNomEtablissement(),0,0,'C');
            
            
             $tplId = $pdf->importPage(8);

             $pdf->AddPage ();
             $pdf->useTemplate($tplId);
            //Ecrire sur le fichier
            $pdf->SetFont ('Helvetica');
            $pdf->SetXY(80 ,157);
            //$pdf->Cell(0,0, $pagedegarde->getNumeroCopiebureau(), 0, 0,'C');


            $pdf->Output('F', $newFile); 

            $pagedegarde->setFichier("pages_de_garde_".$pagedegarde->getId().".pdf");
            $entityManager = $this->getDoctrine()->getManager();           
            $entityManager->persist($pagedegarde);
            $entityManager->flush();

            return $this->redirectToRoute('pagedegarde_index');
        }

        return $this->render('pagedegarde/new.html.twig', [
            'pagedegarde' => $pagedegarde,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="pagedegarde_show", methods={"GET"})
     */
    public function show(Pagedegarde $pagedegarde): Response
    {
        return $this->render('pagedegarde/show.html.twig', [
            'pagedegarde' => $pagedegarde,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="pagedegarde_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Pagedegarde $pagedegarde): Response
    {
        $form = $this->createForm(PagedegardeType::class, $pagedegarde);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('pagedegarde_index');
        }

        return $this->render('pagedegarde/edit.html.twig', [
            'pagedegarde' => $pagedegarde,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="pagedegarde_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Pagedegarde $pagedegarde): Response
    {
        if ($this->isCsrfTokenValid('delete'.$pagedegarde->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($pagedegarde);
            $entityManager->flush();
        }

        return $this->redirectToRoute('pagedegarde_index');
    }
}

templates/pagedegarde/_delete_form.html.twig
<form method="post" action="{{ path('pagedegarde_delete', {'id': pagedegarde.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ pagedegarde.id) }}">
    <button class="btn">Delete</button>
</form>

templates/pagedegarde/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/pagedegarde/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Pagedegarde{% endblock %}

{% block body %}
    <h1>Edit Pagedegarde</h1>

    {{ include('pagedegarde/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('pagedegarde_index') }}">back to list</a>

    {{ include('pagedegarde/_delete_form.html.twig') }}
{% endblock %}

templates/pagedegarde/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Pagedegarde index{% endblock %}

{% block body %}
    

    <table class="table jumbotron">
        <thead>
            <tr>
                <th>Id</th>
                <th>Numero_copieoriginal</th>
                <th>Numero_copie1</th>
                <th>Numero_copie2</th>
                <th>Numero_copie3</th>
                <th>Numero_copie4</th>
                <th>Numero_copie5</th>
                <th>Numero_copiebureau</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for pagedegarde in pagedegardes %}
            <tr>
                <td>{{ pagedegarde.id }}</td>
                <td>{{ pagedegarde.numeroCopieoriginal }}</td>
                <td>{{ pagedegarde.numeroCopie1 }}</td>
                <td>{{ pagedegarde.numeroCopie2 }}</td>
                <td>{{ pagedegarde.numeroCopie3 }}</td>
                <td>{{ pagedegarde.numeroCopie4 }}</td>
                <td>{{ pagedegarde.numeroCopie5 }}</td>
                <td>{{ pagedegarde.numeroCopiebureau }}</td>
                <td>{{ pagedegarde.nomEtablissement }}</td>
                <td><a href="{{ asset("page_de_garde/" ~ pagedegarde.fichier) }}" target = "_blank" >Visualiser</a></td>
                <td>
                    <a href="{{ path('pagedegarde_show', {'id': pagedegarde.id}) }}">show</a>
                    <a href="{{ path('pagedegarde_edit', {'id': pagedegarde.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="9">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('pagedegarde_new') }}">Create new</a>
{% endblock %}

templates/pagedegarde/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Pagedegarde{% endblock %}

{% block body %}
    <h1>Create new Pagedegarde</h1>

    {{ include('pagedegarde/_form.html.twig') }}

    <a href="{{ path('pagedegarde_index') }}">back to list</a>
{% endblock %}

templates/pagedegarde/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Pagedegarde{% endblock %}

{% block body %}
    <h1>Pagedegarde</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ pagedegarde.id }}</td>
            </tr>
            <tr>
                <th>Numero_copieoriginal</th>
                <td>{{ pagedegarde.numeroCopieoriginal }}</td>
            </tr>
            <tr>
                <th>Numero_copie1</th>
                <td>{{ pagedegarde.numeroCopie1 }}</td>
            </tr>
            <tr>
                <th>Numero_copie2</th>
                <td>{{ pagedegarde.numeroCopie2 }}</td>
            </tr>
            <tr>
                <th>Numero_copie3</th>
                <td>{{ pagedegarde.numeroCopie3 }}</td>
            </tr>
            <tr>
                <th>Numero_copie4</th>
                <td>{{ pagedegarde.numeroCopie4 }}</td>
            </tr>
            <tr>
                <th>Numero_copie5</th>
                <td>{{ pagedegarde.numeroCopie5 }}</td>
            </tr>
            <tr>
                <th>Numero_copiebureau</th>
                <td>{{ pagedegarde.numeroCopiebureau }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('pagedegarde_index') }}">back to list</a>

    <a href="{{ path('pagedegarde_edit', {'id': pagedegarde.id}) }}">edit</a>

    {{ include('pagedegarde/_delete_form.html.twig') }}
{% endblock %}