src/Entity/Dossieradministratif.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\DossieradministratifRepository")
 */
class Dossieradministratif
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $nom_etablissement;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $numero_offre;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $fichier;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomEtablissement(): ?string
    {
        return $this->nom_etablissement;
    }

    public function setNomEtablissement(?string $nom_etablissement): self
    {
        $this->nom_etablissement = $nom_etablissement;

        return $this;
    }

    public function getNumeroOffre(): ?string
    {
        return $this->numero_offre;
    }

    public function setNumeroOffre(?string $numero_offre): self
    {
        $this->numero_offre = $numero_offre;

        return $this;
    }

    public function getFichier(): ?string
    {
        return $this->fichier;
    }

    public function setFichier(?string $fichier): self
    {
        $this->fichier = $fichier;

        return $this;
    }
}

src/Form/DossieradministratifType.php
<?php

namespace App\Form;

use App\Entity\Dossieradministratif;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class DossieradministratifType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom_etablissement')
            ->add('numero_offre')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Dossieradministratif::class,
        ]);
    }
}

src/Controller/DossieradministratifController.php
<?php

namespace App\Controller;

use App\Entity\Dossieradministratif;
use App\Form\DossieradministratifType;
use App\Repository\DossieradministratifRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use setasign\Fpdi\Fpdi ;

/**
 * @Route("/dossieradministratif")
 */
class DossieradministratifController extends AbstractController
{
    /**
     * @Route("/", name="dossieradministratif_index", methods={"GET"})
     */
    public function index(DossieradministratifRepository $dossieradministratifRepository): Response
    {
        return $this->render('dossieradministratif/index.html.twig', [
            'dossieradministratifs' => $dossieradministratifRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="dossieradministratif_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $dossieradministratif = new Dossieradministratif();
        $form = $this->createForm(DossieradministratifType::class, $dossieradministratif);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($dossieradministratif);
            $entityManager->flush();

            $file =  "C:\Users\Djiby sow\Desktop/2IRIS/2iris\public/dossier_administratif/dossier_administratif.pdf";
            
            $newFile = "C:\Users\Djiby sow\Desktop/2IRIS/2iris\public/dossier_administratif/dossier_administratif_".$dossieradministratif->getId().".pdf";
            
            copy($file, $newFile );
            // initie FPDI 
            $pdf = new  Fpdi();
           // ajoute une page 
            $pdf->AddPage();
            // définit le fichier source 
            $pdf->setSourceFile($newFile);
             // page d'importation 1 
             $tplId = $pdf->importPage(1);
            // utilise la page importée et la place au point 10,10 avec une largeur de 100 mm 
            $pdf->useTemplate($tplId);
            //pour la gestion du font
            $pdf->SetFont ('Helvetica','B',12);

            $pdf->SetAutoPageBreak( true );
            $pdf->Output('F', $newFile); 

            

            $dossieradministratif->setFichier("dossieradministratif".$dossieradministratif->getId().".pdf");
            $entityManager->persist($dossieradministratif);
            $entityManager->flush();
            return $this->redirectToRoute('dossieradministratif_index');
        }

        return $this->render('dossieradministratif/new.html.twig', [
            'dossieradministratif' => $dossieradministratif,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="dossieradministratif_show", methods={"GET"})
     */
    public function show(Dossieradministratif $dossieradministratif): Response
    {
        return $this->render('dossieradministratif/show.html.twig', [
            'dossieradministratif' => $dossieradministratif,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="dossieradministratif_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Dossieradministratif $dossieradministratif): Response
    {
        $form = $this->createForm(DossieradministratifType::class, $dossieradministratif);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('dossieradministratif_index');
        }

        return $this->render('dossieradministratif/edit.html.twig', [
            'dossieradministratif' => $dossieradministratif,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="dossieradministratif_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Dossieradministratif $dossieradministratif): Response
    {
        if ($this->isCsrfTokenValid('delete'.$dossieradministratif->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($dossieradministratif);
            $entityManager->flush();
        }

        return $this->redirectToRoute('dossieradministratif_index');
    }
}

templates/dossieradministratif/_delete_form.html.twig
<form method="post" action="{{ path('dossieradministratif_delete', {'id': dossieradministratif.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ dossieradministratif.id) }}">
    <button class="btn">Delete</button>
</form>

templates/dossieradministratif/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/dossieradministratif/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Dossieradministratif{% endblock %}

{% block body %}
    <h1>Edit Dossieradministratif</h1>

    {{ include('dossieradministratif/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('dossieradministratif_index') }}">back to list</a>

    {{ include('dossieradministratif/_delete_form.html.twig') }}
{% endblock %}

templates/dossieradministratif/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Dossieradministratif index{% endblock %}

{% block body %}
    

    <table class="table jumbotron">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom_etablissement</th>
                <th>Numero_offre</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for dossieradministratif in dossieradministratifs %}
            <tr>
                <td>{{ dossieradministratif.id }}</td>
                <td>{{ dossieradministratif.nomEtablissement }}</td>
                <td>{{ dossieradministratif.numeroOffre }}</td>
                 <td><a href="{{ asset("dossier_administratif/" ~ dossieradministratif.fichier) }}" target = "_blank" >Visualiser</a></td>
                <td>
                    <a href="{{ path('dossieradministratif_show', {'id': dossieradministratif.id}) }}">show</a>
                    <a href="{{ path('dossieradministratif_edit', {'id': dossieradministratif.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('dossieradministratif_new') }}">Create new</a>
{% endblock %}

templates/dossieradministratif/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Dossieradministratif{% endblock %}

{% block body %}
    <h1>Create new Dossieradministratif</h1>

    {{ include('dossieradministratif/_form.html.twig') }}

    <a href="{{ path('dossieradministratif_index') }}">back to list</a>
{% endblock %}

templates/dossieradministratif/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Dossieradministratif{% endblock %}

{% block body %}
    <h1>Dossieradministratif</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ dossieradministratif.id }}</td>
            </tr>
            <tr>
                <th>Nom_etablissement</th>
                <td>{{ dossieradministratif.nomEtablissement }}</td>
            </tr>
            <tr>
                <th>Numero_offre</th>
                <td>{{ dossieradministratif.numeroOffre }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('dossieradministratif_index') }}">back to list</a>

    <a href="{{ path('dossieradministratif_edit', {'id': dossieradministratif.id}) }}">edit</a>

    {{ include('dossieradministratif/_delete_form.html.twig') }}
{% endblock %}