src/Entity/LettreDeRetrait.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\LettreDeRetraitRepository")
 */
class LettreDeRetrait
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="date")
     */
    private $date;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $lieu;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $destinataire;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adr_desti;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $reference;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $num_offre;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $fichier;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getLieu(): ?string
    {
        return $this->lieu;
    }

    public function setLieu(string $lieu): self
    {
        $this->lieu = $lieu;

        return $this;
    }

    public function getDestinataire(): ?string
    {
        return $this->destinataire;
    }

    public function setDestinataire(string $destinataire): self
    {
        $this->destinataire = $destinataire;

        return $this;
    }

    public function getAdrDesti(): ?string
    {
        return $this->adr_desti;
    }

    public function setAdrDesti(string $adr_desti): self
    {
        $this->adr_desti = $adr_desti;

        return $this;
    }

    public function getReference(): ?string
    {
        return $this->reference;
    }

    public function setReference(string $reference): self
    {
        $this->reference = $reference;

        return $this;
    }

    public function getNumOffre(): ?string
    {
        return $this->num_offre;
    }

    public function setNumOffre(string $num_offre): self
    {
        $this->num_offre = $num_offre;

        return $this;
    }

    public function getFichier(): ?string
    {
        return $this->fichier;
    }

    public function setFichier(?string $fichier): self
    {
        $this->fichier = $fichier;

        return $this;
    }
}

src/Form/LettreDeRetraitType.php
<?php

namespace App\Form;

use App\Entity\LettreDeRetrait;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;


class LettreDeRetraitType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('date', DateType::class, [
                'years' => range(2005, 2100),
            ])
            ->add('lieu')
            ->add('destinataire')
            ->add('adr_desti')
            ->add('reference')
            ->add('num_offre')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => LettreDeRetrait::class,
        ]);
    }
}

src/Controller/LettreDeRetraitController.php
<?php

namespace App\Controller;

use App\Entity\LettreDeRetrait;
use App\Form\LettreDeRetraitType;
use App\Repository\LettreDeRetraitRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use setasign\Fpdi\Fpdi ;
use App\Service\FichierLettreDeRetait;



/**
 * @Route("/lettre/de/retrait")
 */
class LettreDeRetraitController extends AbstractController
{
    /**
     * @Route("/", name="lettre_de_retrait_index", methods={"GET"})
     */
    public function index(LettreDeRetraitRepository $lettreDeRetraitRepository): Response
    {
        return $this->render('lettre_de_retrait/index.html.twig', [
            'lettre_de_retraits' => $lettreDeRetraitRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="lettre_de_retrait_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $lettreDeRetrait = new LettreDeRetrait();
        $form = $this->createForm(LettreDeRetraitType::class, $lettreDeRetrait);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();           
            $entityManager->persist($lettreDeRetrait);
            $entityManager->flush();


            $file =  "C:\Users\Djiby sow\Desktop/2IRIS/2iris\public/documents/cahier_de_charge.pdf";
            
            $newFile = "C:\Users\Djiby sow\Desktop/2IRIS/2iris\public/documents/cahier_de_charge_".$lettreDeRetrait->getId().".pdf";
            
            copy($file, $newFile );
            // initie FPDI 
            $pdf = new  Fpdi();
           // ajoute une page 
            $pdf->AddPage();
            // définit le fichier source 
            $pdf->setSourceFile($newFile);
             // page d'importation 1 
             $tplId = $pdf->importPage(1);
            // utilise la page importée et la place au point 10,10 avec une largeur de 100 mm 
            $pdf->useTemplate($tplId);
            //pour la gestion du font
            $pdf->SetFont ('Helvetica','B',12);

            $pdf->SetAutoPageBreak( true );


            //pour la gestion de la position
            $pdf->SetXY(14 ,10);
            $pdf->Cell(280,86, $lettreDeRetrait->getLieu(). ' le '. $lettreDeRetrait->getDate()->format('d M Y') , 0, 0,'C');
            //Ecrire sur le fichier
            //$pdf->Write( 8 , $lettreDeRetrait->getLieu(). ' le '. $lettreDeRetrait->getDate()->format('d M Y'));

            //pour la gestion de la position
            $pdf->SetXY(10 ,18);
            $pdf->Cell(180,140, $lettreDeRetrait->getDestinataire() , 0, 0,'C');
            //Ecrire sur le fichier
            //$pdf->Write( 8 , $lettreDeRetrait->getDestinataire());
            

            //pour la gestion de la position
            $pdf->SetXY(10 ,18);
            $pdf->Cell(180,150, $lettreDeRetrait->getAdrDesti() , 0, 0,'C');
            //Ecrire sur le fichier
            //$pdf->Write( 8 , $lettreDeRetrait->getAdrDesti());
            

            //pour la gestion de la position
            $pdf->SetXY(10 ,18);
            $pdf->Cell(100,191, $lettreDeRetrait->getReference() , 0, 0,'C');
            //Ecrire sur le fichier
            //$pdf->Write( 8 , $lettreDeRetrait->getReference());

            //pour la gestion de la position
            $pdf->SetXY(80 ,157);
            $pdf->Cell(0,0, $lettreDeRetrait->getNumOffre() , 0, 1,'C');
            
            //Ecrire sur le fichier
           // $pdf->Write( 8 , $lettreDeRetrait->getNumOffre());


            $pdf->Output('F', $newFile); 

            $lettreDeRetrait->setFichier("cahier_de_charge_".$lettreDeRetrait->getId().".pdf");
            $entityManager = $this->getDoctrine()->getManager();           
            $entityManager->persist($lettreDeRetrait);
            $entityManager->flush();
            
            return $this->redirectToRoute('lettre_de_retrait_index');
        }

        return $this->render('lettre_de_retrait/new.html.twig', [
            'lettre_de_retrait' => $lettreDeRetrait,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="lettre_de_retrait_show", methods={"GET"})
     */
    public function show(LettreDeRetrait $lettreDeRetrait): Response
    {
        return $this->render('lettre_de_retrait/show.html.twig', [
            'lettre_de_retrait' => $lettreDeRetrait,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="lettre_de_retrait_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, LettreDeRetrait $lettreDeRetrait): Response
    {
        $form = $this->createForm(LettreDeRetraitType::class, $lettreDeRetrait);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('lettre_de_retrait_index');
        }

        return $this->render('lettre_de_retrait/edit.html.twig', [
            'lettre_de_retrait' => $lettreDeRetrait,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="lettre_de_retrait_delete", methods={"DELETE"})
     */
    public function delete(Request $request, LettreDeRetrait $lettreDeRetrait): Response
    {
        if ($this->isCsrfTokenValid('delete'.$lettreDeRetrait->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($lettreDeRetrait);
            $entityManager->flush();
        }

        return $this->redirectToRoute('lettre_de_retrait_index');
    }
}

templates/lettre_de_retrait/_delete_form.html.twig
<form method="post" action="{{ path('lettre_de_retrait_delete', {'id': lettre_de_retrait.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ lettre_de_retrait.id) }}">
    <button class="btn">Delete</button>
</form>

templates/lettre_de_retrait/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/lettre_de_retrait/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit LettreDeRetrait{% endblock %}

{% block body %}
    <div class='jumbotron'>

    {{ include('lettre_de_retrait/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('lettre_de_retrait_index') }}">back to list</a>

    {{ include('lettre_de_retrait/_delete_form.html.twig') }}
    </div>
{% endblock %}

templates/lettre_de_retrait/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}LettreDeRetrait index{% endblock %}

{% block body %}
    

    <table class="table jumbotron">
        <thead>
            <tr>
                <th>Id</th>
                <th>Date</th>
                <th>Lieu</th>
                <th>Destinataire</th>
                <th>Adr_desti</th>
                <th>Reference</th>
                <th>Num_offre</th>
                <th>Nom Fichier</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for lettre_de_retrait in lettre_de_retraits %}
            <tr>
                <td>{{ lettre_de_retrait.id }}</td>
                <td>{{ lettre_de_retrait.date ? lettre_de_retrait.date|date('Y-m-d') : '' }}</td>
                <td>{{ lettre_de_retrait.lieu }}</td>
                <td>{{ lettre_de_retrait.destinataire }}</td>
                <td>{{ lettre_de_retrait.adrDesti }}</td>
                <td>{{ lettre_de_retrait.reference }}</td>
                <td>{{ lettre_de_retrait.numOffre }}</td>
                <td><a href="{{ asset("documents/" ~ lettre_de_retrait.fichier) }}" target = "_blank" >Visualiser</a></td>
                <td>
                    <a href="{{ path('lettre_de_retrait_show', {'id': lettre_de_retrait.id}) }}">show</a>
                    <a href="{{ path('lettre_de_retrait_edit', {'id': lettre_de_retrait.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('lettre_de_retrait_new') }}">Create new</a>
{% endblock %}

templates/lettre_de_retrait/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New LettreDeRetrait{% endblock %}

{% block body %}
    
      <div class='jumbotron'>
    {{ include('lettre_de_retrait/_form.html.twig') }}

    <a href="{{ path('lettre_de_retrait_index') }}">back to list</a>
    </div>
{% endblock %}

templates/lettre_de_retrait/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}LettreDeRetrait{% endblock %}

{% block body %}
    <h1>LettreDeRetrait</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ lettre_de_retrait.id }}</td>
            </tr>
            <tr>
                <th>Date</th>
                <td>{{ lettre_de_retrait.date ? lettre_de_retrait.date|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Lieu</th>
                <td>{{ lettre_de_retrait.lieu }}</td>
            </tr>
            <tr>
                <th>Destinataire</th>
                <td>{{ lettre_de_retrait.destinataire }}</td>
            </tr>
            <tr>
                <th>Adr_desti</th>
                <td>{{ lettre_de_retrait.adrDesti }}</td>
            </tr>
            <tr>
                <th>Reference</th>
                <td>{{ lettre_de_retrait.reference }}</td>
            </tr>
            <tr>
                <th>Num_offre</th>
                <td>{{ lettre_de_retrait.numOffre }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('lettre_de_retrait_index') }}">back to list</a>

    <a href="{{ path('lettre_de_retrait_edit', {'id': lettre_de_retrait.id}) }}">edit</a>

    {{ include('lettre_de_retrait/_delete_form.html.twig') }}
{% endblock %}